### PR TITLE
Fix fact blunder.

### PR DESCRIPTION
**Pull request by nqpz**

### CODE REVIEW

**Comment by Athas** [comment]
Why?

**Comment by nqpz** [comment]
On 2016-04-08 01:33:00, Troels Henriksen wrote:
> Why?

You write about a function `fact`, but you show no function `fact`.

I guess maybe the readers are clever enough to realise what you mean,
but it's still a bit unclear.

**Comment by Athas** [comment]
Oh, right.  Fixed in another commit.

**Comment by nqpz** [comment]
On 2016-04-08 01:51:37, Troels Henriksen wrote:
> Oh, right.  Fixed in another commit.

Gotta go fast!

**Pull request closed without merging**
